#DUAS VARIÁVEIS (A E B) POSSUEM VALORES DISTINTOS (A=5 E B= 10),
#CRIE UM ALGORITMO QUE ARMAZENE ESSES DOIS VALORES NESSAS DUAS VARIÁVEIS,
#E EFETUE A TROCA DOS VALORES DE FORMA QUE A VARIÁVEL A PASSE A POSSUIR
#O VALOR DA VARIÁVEL B E QUE A VARIÁVEL B PASSE A POSSUIR O VALOR DA VARIÁVEL A.
# POR FIM, APRESENTAR OS VALORES TROCADO.

a = 5
b = 10
print(f"O valor de A é: {a} , e  o de B é: {b} ")
troca = a
a = b
b = troca
print(f"AGORA O valor de A é: {a} ,e o de B é: {b} ")