#IMAGINE QUE QUEREMOS IMPRIMIR TODOS AS LETRAS DE UM NOME.
# ENTÃO, FAÇA UM PROGRAMA QUE RECEBA UM NOME DE UMA PESSOAS E MOSTRE LETRA POR LETRA.

nome = input("Digite um nome: ")
for x in nome:
    print(x)